import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "anthropic/index": "src/anthropic/index.ts",
    "openai/index": "src/openai/index.ts",
    "google/index": "src/google/index.ts",
    "vertex/index": "src/vertex/index.ts",
    "ollama/index": "src/ollama/index.ts",
    "openrouter/index": "src/openrouter/index.ts",
    "xai/index": "src/xai/index.ts",
    "groq/index": "src/groq/index.ts",
    "cerebras/index": "src/cerebras/index.ts",
    "moonshot/index": "src/moonshot/index.ts",
    "http/index": "src/http/index.ts",
    "proxy/index": "src/proxy/index.ts",
    "responses/index": "src/responses/index.ts",
    "middleware/logging/index": "src/middleware/logging.ts",
    "middleware/parsed-object/index": "src/middleware/parsed-object.ts",
    "middleware/persistence/index": "src/middleware/persistence.ts",
    "middleware/pipeline/index": "src/middleware/pipeline/index.ts",
    "middleware/pubsub/index": "src/middleware/pubsub/index.ts",
    "middleware/pubsub/server/index": "src/middleware/pubsub/server/index.ts",
    "middleware/pubsub/server/webapi/index": "src/middleware/pubsub/server/webapi.ts",
    "middleware/pubsub/server/express/index": "src/middleware/pubsub/server/express.ts",
    "middleware/pubsub/server/h3/index": "src/middleware/pubsub/server/h3.ts",
    "middleware/pubsub/server/fastify/index": "src/middleware/pubsub/server/fastify.ts",
    "proxy/server/index": "src/proxy/server/index.ts",
    "proxy/server/webapi/index": "src/proxy/server/webapi.ts",
    "proxy/server/express/index": "src/proxy/server/express.ts",
    "proxy/server/h3/index": "src/proxy/server/h3.ts",
    "proxy/server/fastify/index": "src/proxy/server/fastify.ts",
    "utils/index": "src/utils/index.ts",
  },
  format: ["esm"],
  dts: true,
  splitting: true,
  sourcemap: true,
  clean: true,
  target: "esnext",
  outDir: "dist",
});
